### ISSUE TITLE
cntr-fuse mangles bytes on s390x

### ISSUE THREAD

**Issue by nc7s** [Mic92/cntr#356]
This should go to the cntr-fuse repo but it didn't enable issues, so.

Debian CI caught quite some tests [failing on s390x](https://ci.debian.net/packages/r/rust-cntr-fuse/testing/s390x/48329870/#L1299), basically bytes that are supposed to be in the opposite endian in some way. Though my knowledge can't really reason about how that happened.

For example,

```
 53s ---- reply::test::reply_lock stdout ----
 53s thread 'reply::test::reply_lock' panicked at src/reply.rs:866:13:
 53s assertion `left == right` failed
 53s   left: [[40, 0, 0, 0, 0, 0, 0, 0, 239, 190, 173, 222, 0, 0, 0, 0], [17, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 68, 0, 0, 0]]
 53s  right: [[0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 222, 173, 190, 239], [0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0, 51, 0, 0, 0, 68]]
 53s stack backtrace:
 53s    0: rust_begin_unwind
 53s              at /usr/src/rustc-1.78.0/library/std/src/panicking.rs:645:5
 53s    1: core::panicking::panic_fmt
 53s              at /usr/src/rustc-1.78.0/library/core/src/panicking.rs:72:14
 53s    2: core::panicking::assert_failed_inner
 53s              at /usr/src/rustc-1.78.0/library/core/src/panicking.rs:343:17
 53s    3: core::panicking::assert_failed
 53s              at /usr/src/rustc-1.78.0/library/core/src/panicking.rs:298:5
 53s    4: <cntr_fuse::reply::test::AssertSender as cntr_fuse::reply::ReplySender>::send
 53s              at ./src/reply.rs:866:13
 53s    5: cntr_fuse::reply::ReplyRaw<T>::send::{{closure}}
 53s              at ./src/reply.rs:176:13
 53s    6: cntr_fuse::reply::as_bytes
 53s              at ./src/reply.rs:53:13
 53s    7: cntr_fuse::reply::ReplyRaw<T>::send
 53s              at ./src/reply.rs:172:9
 53s    8: cntr_fuse::reply::ReplyRaw<T>::ok::{{closure}}
 53s              at ./src/reply.rs:183:13
 53s    9: cntr_fuse::reply::as_bytes
 53s              at ./src/reply.rs:53:13
 53s   10: cntr_fuse::reply::ReplyRaw<T>::ok
 53s              at ./src/reply.rs:182:9
 53s   11: cntr_fuse::reply::ReplyLock::locked
 53s              at ./src/reply.rs:535:9
 53s   12: cntr_fuse::reply::test::reply_lock
 53s              at ./src/reply.rs:1095:9
 53s   13: cntr_fuse::reply::test::reply_lock::{{closure}}
 53s              at ./src/reply.rs:1086:20
 53s   14: core::ops::function::FnOnce::call_once
 53s              at /usr/src/rustc-1.78.0/library/core/src/ops/function.rs:250:5
 53s   15: core::ops::function::FnOnce::call_once
 53s              at /usr/src/rustc-1.78.0/library/core/src/ops/function.rs:250:5
 53s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 ```

Probably solvable by https://github.com/Mic92/cntr/issues/78.

**Comment by werdahias** [comment]
This is caused by s390x being a big-endian arch. To me it looks like for this specific test the nibbles get sorted BE which causes the subsequent failure,

**Comment by Mic92** [comment]
no more fuse in master.
